### PR TITLE
up to date docusaurus

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/openyurtio/openyurt.io/issues/143

### CODE REVIEW

**Comment by rambohe-ch** [comment]
@luc99hen PTAL

**Comment by luc99hen** [comment]
@Arhell Hi, Arhell.  Is this PR closed for updating?

**Comment by Arhell** [comment]
> @Arhell Hi, Arhell. Is this PR closed for updating? Is it OK to reopen it?

Hello, no, yesterday I made a mistake and deleted the fork repository, no changes here

**Review by luc99hen — APPROVED** [review]

**Pull request merged**
