### PR TITLE
update docs for yurtadm

### PR DESCRIPTION
**Pull request by YTGhost**

### CODE REVIEW

**Comment by YTGhost** [comment]
@rambohe-ch PTAL

**Comment by rambohe-ch** [comment]
@YTGhost The docs under `https://github.com/openyurtio/openyurt.io/tree/master/i18n/zh/docusaurus-plugin-content-docs/current/reference` should also be updated.

**Comment by rambohe-ch** [comment]
@YTGhost Please fix the docs check errors.

**Comment by YTGhost** [comment]
@rambohe-ch PTAL

**Review by rambohe-ch — APPROVED** [review]

**Pull request merged**
