### PR TITLE
use periods instead, in English docs.

### PR DESCRIPTION
**Pull request by fujitatomoya**
minor typo fix for English doc.

Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>

### CODE REVIEW

**Comment by fujitatomoya** [comment]
@rambohe-ch friendly ping!

**Review by Arhell — COMMENTED** [review]
lgtm

**Review by rambohe-ch — APPROVED** [review]

**Comment by fujitatomoya** [comment]
@rambohe-ch thanks for the quick response!

**Comment by rambohe-ch** [comment]
> @rambohe-ch thanks for the quick response!

@fujitatomoya Thank you for posting pull request. and we will update the manually setup tutorial recently.

**Pull request merged**
