### PR TITLE
Add local storage zh doc

### PR DESCRIPTION
**Pull request by mowangdk**

### CODE REVIEW

**Comment by Peeknut** [comment]
Please add docs in `docs`, `i18n/zh/docusaurus-plugin-content-docs/version-v0.5.0`,  `versioned_docs/version-v0.5.0`.
You can only put the Chinese version, we don't want the document to be blank in these places. :)

**Comment by mowangdk** [comment]
> Please add docs in `docs`, `i18n/zh/docusaurus-plugin-content-docs/version-v0.5.0`, `versioned_docs/version-v0.5.0`. You can only put the Chinese version, we don't want the document to be blank in these places. :)

ok

**Comment by mowangdk** [comment]
@Peeknut docs added

**Comment by Peeknut** [comment]
The docs should be added in `docs/user-manuals`, too.:)

**Pull request merged**
